// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afotusbousojuugwfkib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmb3R1c2JvdXNvanV1Z3dma2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTcwNzYsImV4cCI6MjA2ODIzMzA3Nn0.U3Q7Qjxcf9guOhw9uBZIWSQVCxgQO7NDIhKNDveLRik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});